name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'        # Trigger on content changes
      - 'config/**'         # Trigger on static assets
      - 'assets/**'         # Trigger on theme changes
      - 'Dockerfile'        # Trigger on Dockerfile changes
      - 'version.txt'      # Trigger on version changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Read version from file
        id: version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-devops-blog:${{ env.VERSION }}
